[project]
name = "template-mcp-helloworld-python"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "blaxel[core,telemetry]==0.2.19",
  "mcp[cli]>=1.16.0",
]
